"""add foreign key to Review

Revision ID: ca4b907ee531
Revises: db2799c095e1
Create Date: 2024-04-07 16:22:31.143883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4b907ee531'
down_revision = 'db2799c095e1'
branch_labels = None
depends_on = None


def upgrade():
    # Check if the column already exists
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = inspector.get_columns('reviews')
    column_names = [column['name'] for column in columns]
    
    if 'employee_id' not in column_names:
        # Add the column only if it doesn't exist
        op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
        op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
